format = """
[](fg:blue)\
$username\
[](bg:green fg:blue)\
$directory\
[](fg:green bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:cyan)\
$kubernetes\
[](fg:cyan)\
$line_break\
$character"""

# Prevent slow commands from blocking the prompt
command_timeout = 2000

[username]
style_user = "bg:blue fg:black bold"
style_root = "bg:blue fg:red bold"
format = '[$user ]($style)'
disabled = false
show_always = true

[directory]
style = "fg:black bg:green bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow fg:black"
format = '[$all_status$ahead_behind ]($style)'

[kubernetes]
format = '[ ☸ $context\($namespace\) ](bg:cyan fg:black)'
disabled = false
detect_files = ["k8s.yaml", "k8s.yml", "kubeconfig", ".kubeconfig"]
detect_folders = ["k8s", "helm", "charts"]

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"